import { ConceptPlugin, PluginConfig, ConceptEventType, ConceptListener } from '../../dist/types/plugin';
declare class DatabasePlugin implements ConceptPlugin {
    readonly config: PluginConfig;
    private dbConfig;
    private block;
    private indexes;
    setBlock(block: any): void;
    initialize(): Promise<void>;
    cleanup(): Promise<void>;
    registerListeners(): Map<ConceptEventType, ConceptListener>;
    getHooks(): {
        db: (params: any[], block?: any[]) => any[];
    };
    private ensureDatabaseDirectory;
    private getTablePath;
    private parseColumnDefinitions;
    private parseDataFromBlock;
    private createTable;
    private dropTable;
    private listTables;
    private describeTable;
    private insertData;
    private selectData;
    private updateData;
    private deleteData;
    private executeQuery;
    private handleSelectQuery;
    private handleInsertQuery;
    private handleUpdateQuery;
    private handleDeleteQuery;
    private countRecords;
    private findRecords;
    private manageIndex;
    private createIndex;
    private listIndexes;
    private dropIndex;
    private beginTransaction;
    private commitTransaction;
    private rollbackTransaction;
    private createBackup;
    private restoreBackup;
    private listBackups;
    private updateConfig;
    private showStats;
    private exportData;
    private importData;
    private vacuumDatabase;
    private showHelp;
}
export default DatabasePlugin;
